### ISSUE TITLE
My modpack crashes

### ISSUE THREAD

**Issue by DkillsBV** [Focamacho/MyServerIsCompatible#4]
I made a modpack using MyServerIsCompatible and some other mods
But it crashes when starting up.
I went over to SuperMartijns642's discord server to get support since the problem inculded some of the mods they made.
They said i needed to go here since tehy don't know why your mod conflicts with theirs.
The logs and the modpack are added below.

[latest.log](https://github.com/focamacho/MyServerIsCompatible/files/9384429/latest.log)
[Modpack 1.zip](https://github.com/focamacho/MyServerIsCompatible/files/9384431/Modpack.1.zip)

**Comment by SuperMartijn642** [comment]
Some additional info:
On Minecraft 1.12, both My Server Is Compatible and [my core library](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/tree/1.12) work fine independently, but cause a crash when combined.

The crash seems to be caused by a mixin error from my core library. However, I don't see how this is only the case when My Server Is Compatible is installed.
Both mods only have one mixin into different classes (`ForgeHooksClient` and `FMLClientHandler`), so, as far as I know, those shouldn't conflict.
The mixin from my core library can be found here: https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/blob/1.12/src/main/java/com/supermartijn642/core/mixin/LevelRendererMixin.java

**Comment by focamacho** [comment]
Seems like that the mixin versions included in both mods are conflicting? I don't know why, because they seem to have the same version.
Adding this mod to your modpack should fix the issue -> https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by DkillsBV** [comment]
Using that mod seems to work. Thanks for the help!
